// ---------- Valdymo skydelis v3: darbai su keliomis nuotraukomis / video ----------
function rk_galui_page() {
    $nonce = wp_create_nonce('wp_rest');
    ?>
<div id="rkg-app" class="rkg-app">
  <style>
  #wpcontent{background:#F4F7F5}.rkg-app{--g:#166534;--gd:#14532D;--acc:#22C55E;--tx:#111827;--mut:#64748B;--line:#E2E8F0;font-family:Inter,"Segoe UI",system-ui,sans-serif;color:var(--tx);margin:0 20px 90px 0;max-width:1440px}
  .rkg-app *{box-sizing:border-box}.rkg-app button{font-family:inherit}
  .rkg-top{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:24px 0 16px;flex-wrap:wrap}
  .rkg-top h1{margin:0;font-size:26px;font-weight:800;letter-spacing:-.01em;display:flex;align-items:center;gap:12px}.rkg-top h1 .ic{width:42px;height:42px;border-radius:12px;background:var(--g);color:#fff;display:grid;place-items:center}
  .rkg-top p{margin:6px 0 0;color:var(--mut);font-size:13.5px}.rkg-top p b{color:var(--g)}
  .rkg-btn{display:inline-flex;align-items:center;gap:8px;padding:11px 18px;border-radius:11px;font-weight:700;font-size:13.5px;border:1.5px solid transparent;cursor:pointer;line-height:1;transition:.15s;white-space:nowrap}
  .rkg-btn.p{background:var(--acc);color:#052E16}.rkg-btn.p:hover{background:#16a34a}.rkg-btn.g{background:var(--g);color:#fff}.rkg-btn.g:hover{background:var(--gd)}.rkg-btn.o{background:#fff;color:var(--g);border-color:var(--line)}.rkg-btn.o:hover{border-color:var(--g)}.rkg-btn.d{background:#fff;color:#b91c1c;border-color:#fecaca}.rkg-btn.d:hover{background:#fef2f2}.rkg-btn.s{padding:8px 12px;font-size:12.5px;border-radius:9px}.rkg-btn:disabled{opacity:.5;cursor:default}
  .rkg-help{background:#fff;border:1px solid var(--line);border-radius:16px;padding:16px 18px;margin-bottom:16px;display:none}.rkg-help.on{display:block}.rkg-help h3{margin:0 0 10px;font-size:15px}.rkg-help ol{margin:0;padding:0;list-style:none;display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.rkg-help li{display:flex;gap:10px;font-size:13px;color:#334155;line-height:1.5}.rkg-help li i{flex:0 0 26px;height:26px;border-radius:50%;background:var(--g);color:#fff;font-style:normal;font-weight:800;display:grid;place-items:center;font-size:12px}
  .rkg-lay{display:grid;grid-template-columns:270px 1fr;gap:16px;align-items:start}@media(max-width:1100px){.rkg-lay{grid-template-columns:1fr}}
  .rkg-side{background:#fff;border:1px solid var(--line);border-radius:16px;padding:12px;position:sticky;top:46px}.rkg-side h4{margin:4px 8px 8px;font-size:11.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--mut)}
  .rkg-cat{display:flex;align-items:center;gap:8px;width:100%;text-align:left;padding:10px 12px;border-radius:11px;border:1.5px solid transparent;background:transparent;cursor:pointer;font-size:13.5px;font-weight:600;color:var(--tx);transition:.15s}.rkg-cat:hover{background:#F8FAFC}.rkg-cat.on{background:var(--g);color:#fff}.rkg-cat b{margin-left:auto;background:#F0FDF4;color:var(--g);border-radius:999px;padding:2px 8px;font-size:11.5px}.rkg-cat.on b{background:rgba(255,255,255,.2);color:#fff}
  .rkg-cat .mv{display:none;gap:2px}.rkg-cat:hover .mv{display:inline-flex}.rkg-cat .mv span{width:20px;height:20px;border-radius:6px;display:grid;place-items:center;font-size:10px;background:#F1F5F9;color:var(--tx)}.rkg-cat.on .mv span{background:rgba(255,255,255,.2);color:#fff}
  .rkg-cat.add{border:1.5px dashed var(--line);color:var(--mut);justify-content:center;margin-top:8px}.rkg-cat.add:hover{border-color:var(--g);color:var(--g)}
  .rkg-side .foot{border-top:1px solid var(--line);margin-top:10px;padding-top:10px;display:flex;flex-direction:column;gap:6px}
  .rkg-main{min-width:0}
  .rkg-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:12px}.rkg-head h2{margin:0;font-size:20px;font-weight:800;display:flex;align-items:center;gap:10px}.rkg-head h2 small{font-size:12.5px;color:var(--mut);font-weight:600}.rkg-head .r{display:flex;gap:8px;flex-wrap:wrap;align-items:center}
  .rkg-head input[type=text]{border:1.5px solid var(--line);border-radius:9px;padding:9px 12px;font-size:13px;background:#fff;min-width:220px}
  .rkg-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:14px}
  .rkg-card{background:#fff;border:1px solid var(--line);border-radius:14px;overflow:hidden;position:relative;transition:.15s;display:flex;flex-direction:column}.rkg-card:hover{box-shadow:0 18px 40px -22px rgba(15,74,40,.35)}
  .rkg-card .ph{aspect-ratio:4/3;background:#0f172a center/cover no-repeat;cursor:pointer;position:relative}.rkg-card .ph .n{position:absolute;left:10px;bottom:10px;background:rgba(17,24,39,.72);color:#fff;font-size:11px;font-weight:700;padding:4px 8px;border-radius:999px}.rkg-card .ph .play{position:absolute;top:50%;left:50%;width:40px;height:40px;margin:-20px 0 0 -20px;border-radius:50%;background:rgba(255,255,255,.92);color:var(--g);display:grid;place-items:center;font-size:15px;padding-left:3px}
  .rkg-card .ph .mv{position:absolute;right:8px;top:8px;display:flex;gap:4px;opacity:0;transition:.15s}.rkg-card:hover .ph .mv{opacity:1}.rkg-card .ph .mv button{width:28px;height:28px;border-radius:8px;background:rgba(255,255,255,.95);border:0;color:var(--tx);cursor:pointer;font-size:12px;display:grid;place-items:center}.rkg-card .ph .mv button:disabled{opacity:.35}
  .rkg-card .bd{padding:10px 12px 12px;display:flex;flex-direction:column;gap:8px}.rkg-card .t{font-weight:600;font-size:13px;line-height:1.35;min-height:35px}.rkg-card .act{display:flex;gap:6px}.rkg-card .act .rkg-btn{flex:1;justify-content:center}
  .rkg-empty{background:#fff;border:1px dashed var(--line);border-radius:16px;padding:40px;text-align:center;color:var(--mut)}
  .rkg-modal{position:fixed;inset:0;background:rgba(17,24,39,.55);z-index:100000;display:none;align-items:flex-start;justify-content:center;padding:30px 16px;overflow:auto}.rkg-modal.on{display:flex}
  .rkg-modal .box{background:#fff;border-radius:18px;width:100%;max-width:920px;padding:22px;box-shadow:0 30px 80px rgba(0,0,0,.35)}.rkg-modal h3{margin:0 0 14px;font-size:19px;font-weight:800;display:flex;justify-content:space-between;align-items:center}.rkg-modal h3 button{border:0;background:#F1F5F9;width:34px;height:34px;border-radius:50%;cursor:pointer;font-size:16px}
  .rkg-modal label{display:block;font-size:12.5px;font-weight:700;color:#334155;margin:12px 0 5px}.rkg-modal input[type=text],.rkg-modal select,.rkg-modal textarea{width:100%;border:1.5px solid var(--line);border-radius:10px;padding:10px 12px;font-size:14px;font-family:inherit;background:#fff}.rkg-modal input:focus,.rkg-modal select:focus,.rkg-modal textarea:focus{border-color:var(--acc);outline:0}
  .rkg-modal .two{display:grid;grid-template-columns:1fr 260px;gap:14px}@media(max-width:700px){.rkg-modal .two{grid-template-columns:1fr}}
  .rkg-drop{border:2px dashed #BBF7D0;background:#F0FDF4;border-radius:14px;padding:18px;text-align:center;color:var(--g);font-weight:700;margin-top:12px;cursor:pointer;transition:.15s;font-size:13.5px}.rkg-drop:hover,.rkg-drop.over{background:#DCFCE7;border-color:var(--acc)}.rkg-drop small{display:block;color:var(--mut);font-weight:500;margin-top:4px;font-size:12px}
  .rkg-media{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:10px;margin-top:12px}
  .rkg-m{position:relative;border:1.5px solid var(--line);border-radius:10px;overflow:hidden;background:#0f172a;aspect-ratio:4/3}.rkg-m img,.rkg-m video{width:100%;height:100%;object-fit:cover;display:block}.rkg-m.cov{border-color:var(--acc);box-shadow:0 0 0 2px #BBF7D0}
  .rkg-m .tag{position:absolute;left:6px;top:6px;background:rgba(17,24,39,.75);color:#fff;font-size:10px;font-weight:700;padding:2px 6px;border-radius:999px}.rkg-m .tag.v{background:#b91c1c}
  .rkg-m .tools{position:absolute;inset:auto 0 0 0;display:flex;justify-content:space-between;padding:5px;background:linear-gradient(transparent,rgba(0,0,0,.6));opacity:0;transition:.15s}.rkg-m:hover .tools{opacity:1}.rkg-m .tools button{width:24px;height:24px;border-radius:6px;border:0;background:rgba(255,255,255,.95);cursor:pointer;font-size:11px;display:grid;place-items:center;color:var(--tx)}.rkg-m .tools button.x{color:#b91c1c}.rkg-m .tools button.c{color:var(--g)}
  .rkg-m .up{position:absolute;inset:0;background:rgba(17,24,39,.7);color:#fff;display:grid;place-items:center;font-size:12px;font-weight:700}
  .rkg-modal .foot{display:flex;justify-content:space-between;gap:10px;margin-top:18px;flex-wrap:wrap}
  #rkg-toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#111827;color:#fff;padding:12px 18px;border-radius:12px;font-size:13.5px;font-weight:600;z-index:100001;display:none;box-shadow:0 20px 50px rgba(0,0,0,.3)}#rkg-toast.on{display:block}#rkg-toast.err{background:#b91c1c}
  </style>
  <div class="rkg-top"><div><h1><span class="ic">&#9635;</span>Galerija – atlikti darbai</h1><p>Vienas darbas = pavadinimas (markė, modelis, kas atlikta) + kelios nuotraukos ir/arba video. Svetainėje rodoma viena kortelė, paspaudus – visos to darbo nuotraukos. <b id="rkg-sum"></b></p></div>
    <div style="display:flex;gap:8px;flex-wrap:wrap"><button class="rkg-btn o" id="rkg-helpb">? Kaip naudotis</button><button class="rkg-btn p" id="rkg-new">+ Naujas darbas</button></div></div>
  <div class="rkg-help" id="rkg-help"><h3>Kaip naudotis</h3><ol>
    <li><i>1</i>Kairėje pasirinkite kategoriją (paslaugą). Kategorijų eiliškumas (↑↓) = eiliškumas svetainėje.</li>
    <li><i>2</i>„+ Naujas darbas“ → įrašykite pavadinimą (pvz. „Audi Q5 2018 m. antro rakto gamyba“), pasirinkite kategoriją, įkelkite nuotraukas ir video (galima kelis iš karto).</li>
    <li><i>3</i>Nuotraukų tvarką keiskite rodyklėmis, ★ pažymėkite viršelį (rodomas kortelėje). Video rodomas su ▶ ženklu.</li>
    <li><i>4</i>„Išsaugoti“ – darbas iš karto matomas svetainėje. Kortelių eiliškumą keiskite rodyklėmis ant kortelės.</li>
  </ol></div>
  <div class="rkg-lay">
    <aside class="rkg-side"><h4>Kategorijos</h4><div id="rkg-cats"></div><button class="rkg-cat add" id="rkg-addcat">+ Nauja kategorija</button>
      <div class="foot"><button class="rkg-btn o s" id="rkg-editcat">Kategorijos nustatymai</button></div></aside>
    <main class="rkg-main"><div class="rkg-head"><h2 id="rkg-title">Visi darbai <small id="rkg-cnt"></small></h2><div class="r"><input type="text" id="rkg-q" placeholder="Ieškoti pagal pavadinimą…"></div></div><div id="rkg-list" class="rkg-grid"></div></main>
  </div>
  <div class="rkg-modal" id="rkg-ed"><div class="box"><h3><span id="rkg-ed-title">Naujas darbas</span><button type="button" id="rkg-ed-x">✕</button></h3>
    <div class="two"><div><label>Pavadinimas (markė, modelis, metai, kas atlikta)</label><input type="text" id="rkg-f-title" placeholder="pvz. Audi Q5 2018 m. antro rakto gamyba"></div>
      <div><label>Kategorija</label><select id="rkg-f-cat"></select></div></div>
    <div class="rkg-drop" id="rkg-drop">Įkelti nuotraukas / video<small>Spustelėkite arba nutempkite failus čia (JPG, PNG, MP4, MOV – galima kelis iš karto)</small></div><input type="file" id="rkg-file" multiple accept="image/*,video/mp4,video/quicktime" style="display:none">
    <div class="rkg-media" id="rkg-media"></div>
    <div class="foot"><button class="rkg-btn d" id="rkg-del" style="display:none">Ištrinti darbą</button><div style="display:flex;gap:8px;margin-left:auto"><button class="rkg-btn o" id="rkg-cancel">Atšaukti</button><button class="rkg-btn g" id="rkg-save">Išsaugoti</button></div></div>
  </div></div>
  <div class="rkg-modal" id="rkg-cm"><div class="box" style="max-width:560px"><h3><span id="rkg-cm-title">Kategorija</span><button type="button" id="rkg-cm-x">✕</button></h3>
    <label>Pavadinimas</label><input type="text" id="rkg-c-name"><label>Rodyti paslaugos puslapyje</label><select id="rkg-c-page"><option value="0">– nerodyti atskirame puslapyje (tik „Atlikti darbai“) –</option></select>
    <div class="foot"><button class="rkg-btn d" id="rkg-c-del">Ištrinti kategoriją</button><div style="display:flex;gap:8px;margin-left:auto"><button class="rkg-btn o" id="rkg-c-cancel">Atšaukti</button><button class="rkg-btn g" id="rkg-c-save">Išsaugoti</button></div></div>
  </div></div>
  <div id="rkg-toast"></div>
</div>
<script>
(function(){
var N='<?php echo esc_js($nonce); ?>',R='<?php echo esc_js(rest_url('wp/v2/')); ?>',$=function(s){return document.querySelector(s)};
var S={cats:[],pages:[],jobs:[],cat:0,q:'',edit:null,media:[],cover:0,busy:0};
function api(p,o){o=o||{};var h={'X-WP-Nonce':N};if(!(o.body instanceof FormData))h['Content-Type']='application/json';return fetch(R+p,{method:o.method||'GET',headers:h,body:o.body instanceof FormData?o.body:(o.body?JSON.stringify(o.body):undefined),credentials:'same-origin'}).then(function(r){return r.json().then(function(j){if(!r.ok)throw new Error(j.message||r.status);return j})})}
function toast(t,err){var e=$('#rkg-toast');e.textContent=t;e.className='on'+(err?' err':'');clearTimeout(e._t);e._t=setTimeout(function(){e.className=''},3200)}
function dec(s){var d=document.createElement('textarea');d.innerHTML=s;return d.value}
function esc(s){return String(s).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function load(){return Promise.all([api('rk_gal_kat?per_page=100&hide_empty=false&context=edit'),api('pages?per_page=100&_fields=id,title,parent&status=publish'),loadJobs()]).then(function(r){S.cats=r[0].map(function(c){return{id:c.id,name:dec(c.name),slug:c.slug,count:c.count,page:(c.meta&&c.meta.rk_page)||0,order:(c.meta&&c.meta.rk_order)||999}}).sort(function(a,b){return a.order-b.order||a.name.localeCompare(b.name)});S.pages=r[1];render()})}
function loadJobs(){var all=[],pg=1;function nx(){return api('rk_galerija?per_page=100&page='+pg+'&context=edit&orderby=menu_order&order=asc&_fields=id,title,menu_order,rk_gal_kat,featured_media,meta').then(function(j){all=all.concat(j);if(j.length===100){pg++;return nx()}})}return nx().then(function(){S.jobs=all.map(function(p){var m=[];try{m=JSON.parse((p.meta&&p.meta.rk_media)||'[]')}catch(e){}return{id:p.id,title:dec(p.title.raw||p.title.rendered),order:p.menu_order,cat:(p.rk_gal_kat||[])[0]||0,cover:p.featured_media,media:m}})})}
var thumbCache={};function thumb(id){if(thumbCache[id])return Promise.resolve(thumbCache[id]);return api('media/'+id+'?_fields=id,source_url,media_details,mime_type').then(function(m){var s=m.media_details&&m.media_details.sizes;var u=(s&&(s.medium_large||s.medium||s.large)&&(s.medium_large||s.medium||s.large).source_url)||m.source_url;thumbCache[id]={url:u,full:m.source_url,video:/^video/.test(m.mime_type)};return thumbCache[id]}).catch(function(){return{url:'',full:'',video:false}})}
function render(){var cs=$('#rkg-cats');var total=S.jobs.length;cs.innerHTML='<button class="rkg-cat'+(S.cat===0?' on':'')+'" data-id="0">Visi darbai<b>'+total+'</b></button>'+S.cats.map(function(c,i){var n=S.jobs.filter(function(j){return j.cat===c.id}).length;return'<button class="rkg-cat'+(S.cat===c.id?' on':'')+'" data-id="'+c.id+'"><span class="mv"><span data-mv="-1" title="Aukštyn">▲</span><span data-mv="1" title="Žemyn">▼</span></span>'+esc(c.name)+'<b>'+n+'</b></button>'}).join('');
 cs.querySelectorAll('.rkg-cat').forEach(function(b){b.addEventListener('click',function(e){var mv=e.target.getAttribute('data-mv');if(mv){e.stopPropagation();moveCat(+b.getAttribute('data-id'),+mv);return}S.cat=+b.getAttribute('data-id');render()})});
 var c=S.cats.filter(function(x){return x.id===S.cat})[0];$('#rkg-title').firstChild.textContent=(c?c.name:'Visi darbai')+' ';
 var list=S.jobs.filter(function(j){return(!S.cat||j.cat===S.cat)&&(!S.q||j.title.toLowerCase().indexOf(S.q)>=0)});$('#rkg-cnt').textContent=list.length+' darb.';
 var ni=S.jobs.reduce(function(a,j){return a+j.media.filter(function(m){return m.t!=='v'}).length},0),nv=S.jobs.reduce(function(a,j){return a+j.media.filter(function(m){return m.t==='v'}).length},0);$('#rkg-sum').textContent=total+' darbai · '+ni+' nuotr. · '+nv+' video';
 var L=$('#rkg-list');if(!list.length){L.innerHTML='<div class="rkg-empty" style="grid-column:1/-1">Šioje kategorijoje darbų dar nėra. Spauskite „+ Naujas darbas“.</div>';return}
 L.innerHTML=list.map(function(j,i){var ni=j.media.filter(function(m){return m.t!=='v'}).length,nv=j.media.filter(function(m){return m.t==='v'}).length;return'<div class="rkg-card" data-id="'+j.id+'"><div class="ph" data-th="'+(j.cover||(j.media[0]&&j.media[0].id)||0)+'">'+(nv?'<span class="play">▶</span>':'')+'<span class="n">'+(ni?ni+' nuotr.':'')+(ni&&nv?' · ':'')+(nv?nv+' video':'')+'</span><span class="mv"><button data-mv="-1" '+(i===0?'disabled':'')+' title="Ankstesnis">◀</button><button data-mv="1" '+(i===list.length-1?'disabled':'')+' title="Vėlesnis">▶</button></span></div><div class="bd"><div class="t">'+esc(j.title)+'</div><div class="act"><button class="rkg-btn o s" data-ed>Redaguoti</button></div></div></div>'}).join('');
 L.querySelectorAll('.rkg-card').forEach(function(card){var id=+card.getAttribute('data-id');var ph=card.querySelector('.ph');var th=+ph.getAttribute('data-th');if(th)thumb(th).then(function(t){if(t.url)ph.style.backgroundImage='url("'+t.url+'")'});ph.addEventListener('click',function(e){if(e.target.closest('[data-mv]'))return;openEdit(id)});card.querySelector('[data-ed]').addEventListener('click',function(){openEdit(id)});card.querySelectorAll('[data-mv]').forEach(function(b){b.addEventListener('click',function(){moveJob(id,+b.getAttribute('data-mv'),list)})})})}
function moveCat(id,d){var i=S.cats.findIndex(function(c){return c.id===id}),j=i+d;if(j<0||j>=S.cats.length)return;var a=S.cats[i];S.cats.splice(i,1);S.cats.splice(j,0,a);Promise.all(S.cats.map(function(c,k){c.order=k+1;return api('rk_gal_kat/'+c.id,{method:'POST',body:{meta:{rk_order:k+1}}})})).then(function(){render();toast('Kategorijų eiliškumas išsaugotas')}).catch(function(e){toast('Klaida: '+e.message,1)})}
function moveJob(id,d,list){var i=list.findIndex(function(j){return j.id===id}),j=i+d;if(j<0||j>=list.length)return;var a=list[i],b=list[j];var oa=a.order,ob=b.order;if(oa===ob)ob=oa+d;a.order=ob;b.order=oa;Promise.all([api('rk_galerija/'+a.id,{method:'POST',body:{menu_order:a.order}}),api('rk_galerija/'+b.id,{method:'POST',body:{menu_order:b.order}})]).then(function(){S.jobs.sort(function(x,y){return x.order-y.order||y.id-x.id});render()}).catch(function(e){toast('Klaida: '+e.message,1)})}
function openEdit(id){var j=S.jobs.filter(function(x){return x.id===id})[0];S.edit=j||null;S.media=j?j.media.map(function(m){var o={t:m.t,id:m.id};if(m.p)o.p=m.p;return o}):[];S.cover=j?j.cover:0;$('#rkg-ed-title').textContent=j?'Redaguoti darbą':'Naujas darbas';$('#rkg-f-title').value=j?j.title:'';var sel=$('#rkg-f-cat');sel.innerHTML=S.cats.map(function(c){return'<option value="'+c.id+'">'+esc(c.name)+'</option>'}).join('');sel.value=j?j.cat:(S.cat||(S.cats[0]&&S.cats[0].id));$('#rkg-del').style.display=j?'':'none';renderMedia();$('#rkg-ed').classList.add('on');$('#rkg-f-title').focus()}
function closeEdit(){$('#rkg-ed').classList.remove('on');S.edit=null;S.media=[]}
function renderMedia(){var M=$('#rkg-media');M.innerHTML=S.media.map(function(m,i){return'<div class="rkg-m'+(m.id===S.cover?' cov':'')+'" data-i="'+i+'"><span class="tag'+(m.t==='v'?' v':'')+'">'+(m.t==='v'?'VIDEO':(m.id===S.cover?'VIRŠELIS':'nuotr.'))+'</span>'+(m.up?'<div class="up">'+m.up+'</div>':'')+'<div class="tools"><span><button data-a="l" '+(i===0?'disabled':'')+'>◀</button><button data-a="r" '+(i===S.media.length-1?'disabled':'')+'>▶</button></span><span>'+(m.t!=='v'?'<button data-a="c" class="c" title="Viršelis">★</button>':'')+'<button data-a="x" class="x" title="Pašalinti">✕</button></span></div></div>'}).join('');
 M.querySelectorAll('.rkg-m').forEach(function(el){var i=+el.getAttribute('data-i'),m=S.media[i];if(m.id)thumb(m.p||m.id).then(function(t){if(m.t==='v'&&!m.p){var v=document.createElement('video');v.src=t.full;v.muted=true;v.preload='metadata';el.insertBefore(v,el.firstChild)}else if(t.url){var im=document.createElement('img');im.src=t.url;el.insertBefore(im,el.firstChild)}});el.querySelectorAll('[data-a]').forEach(function(b){b.addEventListener('click',function(){var a=b.getAttribute('data-a');if(a==='x'){S.media.splice(i,1);if(S.cover===m.id)S.cover=0}if(a==='c')S.cover=m.id;if(a==='l'){S.media.splice(i-1,0,S.media.splice(i,1)[0])}if(a==='r'){S.media.splice(i+1,0,S.media.splice(i,1)[0])}renderMedia()})})})}
function shrink(f){return new Promise(function(res){if(!/^image\/(jpeg|png|webp)$/.test(f.type)||f.size<600*1024)return res(f);var img=new Image(),u=URL.createObjectURL(f);img.onload=function(){var MAX=1800,w=img.width,h=img.height;if(Math.max(w,h)<=MAX&&f.size<2.5*1024*1024){URL.revokeObjectURL(u);return res(f)}var k=Math.min(1,MAX/Math.max(w,h)),cv=document.createElement('canvas');cv.width=Math.round(w*k);cv.height=Math.round(h*k);cv.getContext('2d').drawImage(img,0,0,cv.width,cv.height);cv.toBlob(function(b){URL.revokeObjectURL(u);if(!b)return res(f);var nf=new File([b],f.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'});res(nf.size<f.size?nf:f)},'image/jpeg',.86)};img.onerror=function(){URL.revokeObjectURL(u);res(f)};img.src=u})}
function capture(f){return new Promise(function(res){try{var v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';var u=URL.createObjectURL(f);var done=false;function fin(b){if(done)return;done=true;URL.revokeObjectURL(u);res(b)}v.addEventListener('loadeddata',function(){try{v.currentTime=Math.min(1,(v.duration||2)/2)}catch(e){fin(null)}});v.addEventListener('seeked',function(){try{var cv=document.createElement('canvas');var k=Math.min(1,1200/Math.max(v.videoWidth,v.videoHeight));cv.width=Math.round(v.videoWidth*k);cv.height=Math.round(v.videoHeight*k);cv.getContext('2d').drawImage(v,0,0,cv.width,cv.height);cv.toBlob(function(b){fin(b)},'image/jpeg',.85)}catch(e){fin(null)}});v.addEventListener('error',function(){fin(null)});setTimeout(function(){fin(null)},15000);v.src=u}catch(e){res(null)}})}
function addFiles(files){Array.prototype.forEach.call(files,function(f){var isV=/^video\//.test(f.type)||/\.(mp4|mov)$/i.test(f.name);if(!isV&&!/^image\//.test(f.type))return;var m={t:isV?'v':'i',id:0,up:'Keliama…'};S.media.push(m);renderMedia();(isV?Promise.resolve(f):shrink(f)).then(function(ff){var fd=new FormData();fd.append('file',ff,ff.name);fd.append('title',$('#rkg-f-title').value||ff.name);return api('media',{method:'POST',body:fd})}).then(function(r){m.id=r.id;thumbCache[r.id]={url:(r.media_details&&r.media_details.sizes&&(r.media_details.sizes.medium_large||r.media_details.sizes.medium)&&(r.media_details.sizes.medium_large||r.media_details.sizes.medium).source_url)||r.source_url,full:r.source_url,video:isV};if(!S.cover&&!isV)S.cover=r.id;if(!isV){delete m.up;renderMedia();return}m.up='Kadras…';renderMedia();return capture(f).then(function(b){if(!b){delete m.up;renderMedia();return}var fd2=new FormData();fd2.append('file',b,f.name.replace(/\.[^.]+$/,'')+'-kadras.jpg');fd2.append('title',$('#rkg-f-title').value||f.name);return api('media',{method:'POST',body:fd2}).then(function(p){m.p=p.id;if(!S.cover)S.cover=p.id}).catch(function(){}).then(function(){delete m.up;renderMedia()})})}).catch(function(e){S.media.splice(S.media.indexOf(m),1);renderMedia();toast('Nepavyko įkelti '+f.name+': '+e.message,1)})})}
function save(){var t=$('#rkg-f-title').value.trim(),cat=+$('#rkg-f-cat').value;if(!t)return toast('Įrašykite pavadinimą',1);if(S.media.some(function(m){return m.up}))return toast('Palaukite, kol įkels failus',1);var med=S.media.filter(function(m){return m.id}).map(function(m){var o={t:m.t,id:m.id};if(m.p)o.p=m.p;return o});if(!med.length)return toast('Įkelkite bent vieną nuotrauką ar video',1);var cover=S.cover;if(!med.some(function(m){return m.id===cover||m.p===cover})){cover=0;med.forEach(function(m){if(!cover&&m.t==='i')cover=m.id});if(!cover)med.forEach(function(m){if(!cover&&m.p)cover=m.p})}
 var body={title:t,status:'publish',rk_gal_kat:[cat],featured_media:cover||0,meta:{rk_media:JSON.stringify(med)}};if(!S.edit)body.menu_order=(S.jobs.reduce(function(a,j){return Math.max(a,j.order)},0)+1);
 $('#rkg-save').disabled=true;api('rk_galerija'+(S.edit?'/'+S.edit.id:''),{method:'POST',body:body}).then(function(){closeEdit();toast('Išsaugota');return loadJobs()}).then(render).catch(function(e){toast('Klaida: '+e.message,1)}).then(function(){$('#rkg-save').disabled=false})}
function delJob(){if(!S.edit||!confirm('Ištrinti darbą „'+S.edit.title+'“? Nuotraukos liks medijos bibliotekoje.'))return;api('rk_galerija/'+S.edit.id,{method:'DELETE'}).then(function(){closeEdit();toast('Ištrinta');return loadJobs()}).then(render).catch(function(e){toast('Klaida: '+e.message,1)})}
var catEdit=null;function openCat(c){catEdit=c||null;$('#rkg-cm-title').textContent=c?'Kategorijos nustatymai':'Nauja kategorija';$('#rkg-c-name').value=c?c.name:'';var s=$('#rkg-c-page');s.innerHTML='<option value="0">– nerodyti atskirame puslapyje (tik „Atlikti darbai“) –</option>'+S.pages.map(function(p){return'<option value="'+p.id+'">'+esc(dec(p.title.rendered))+'</option>'}).join('');s.value=c?c.page:0;$('#rkg-c-del').style.display=c?'':'none';$('#rkg-cm').classList.add('on')}
function saveCat(){var n=$('#rkg-c-name').value.trim(),pg=+$('#rkg-c-page').value;if(!n)return toast('Įrašykite pavadinimą',1);var body={name:n,meta:{rk_page:pg}};if(!catEdit)body.meta.rk_order=S.cats.length+1;api('rk_gal_kat'+(catEdit?'/'+catEdit.id:''),{method:'POST',body:body}).then(function(){$('#rkg-cm').classList.remove('on');toast('Išsaugota');return load()}).catch(function(e){toast('Klaida: '+e.message,1)})}
function delCat(){if(!catEdit)return;var n=S.jobs.filter(function(j){return j.cat===catEdit.id}).length;if(n)return toast('Kategorijoje yra '+n+' darbai – pirma perkelkite juos į kitą kategoriją',1);if(!confirm('Ištrinti kategoriją „'+catEdit.name+'“?'))return;api('rk_gal_kat/'+catEdit.id+'?force=true',{method:'DELETE'}).then(function(){$('#rkg-cm').classList.remove('on');if(S.cat===catEdit.id)S.cat=0;return load()}).catch(function(e){toast('Klaida: '+e.message,1)})}
$('#rkg-helpb').addEventListener('click',function(){$('#rkg-help').classList.toggle('on')});$('#rkg-new').addEventListener('click',function(){openEdit(0)});$('#rkg-ed-x').addEventListener('click',closeEdit);$('#rkg-cancel').addEventListener('click',closeEdit);$('#rkg-save').addEventListener('click',save);$('#rkg-del').addEventListener('click',delJob);
$('#rkg-q').addEventListener('input',function(){S.q=this.value.trim().toLowerCase();render()});
var D=$('#rkg-drop'),F=$('#rkg-file');D.addEventListener('click',function(){F.click()});F.addEventListener('change',function(){addFiles(F.files);F.value=''});['dragenter','dragover'].forEach(function(ev){D.addEventListener(ev,function(e){e.preventDefault();D.classList.add('over')})});['dragleave','drop'].forEach(function(ev){D.addEventListener(ev,function(e){e.preventDefault();D.classList.remove('over')})});D.addEventListener('drop',function(e){addFiles(e.dataTransfer.files)});
$('#rkg-addcat').addEventListener('click',function(){openCat(null)});$('#rkg-editcat').addEventListener('click',function(){var c=S.cats.filter(function(x){return x.id===S.cat})[0];if(!c)return toast('Pasirinkite kategoriją kairėje',1);openCat(c)});$('#rkg-cm-x').addEventListener('click',function(){$('#rkg-cm').classList.remove('on')});$('#rkg-c-cancel').addEventListener('click',function(){$('#rkg-cm').classList.remove('on')});$('#rkg-c-save').addEventListener('click',saveCat);$('#rkg-c-del').addEventListener('click',delCat);
load().catch(function(e){toast('Nepavyko įkelti: '+e.message,1)});
})();
</script>
    <?php
}
