// ===== rk_galui_v2: "Galerija" valdymo skydelis (paprastas klientui, modernus) =====
add_action('init', function () {
    register_term_meta('rk_gal_kat', 'rk_page', array('type' => 'integer', 'single' => true, 'show_in_rest' => true, 'auth_callback' => function () { return current_user_can('manage_categories'); }));
}, 5);
add_action('admin_menu', function () {
    add_menu_page('Galerija', 'Galerija', 'edit_posts', 'rk-galerija', 'rk_galui_page', 'dashicons-format-gallery', 25);
    add_submenu_page('rk-galerija', 'Galerija', 'Valdymas', 'edit_posts', 'rk-galerija', 'rk_galui_page');
}, 20);
add_action('admin_init', function () {
    global $pagenow;
    $pt = isset($_GET['post_type']) ? $_GET['post_type'] : '';
    $tx = isset($_GET['taxonomy']) ? $_GET['taxonomy'] : '';
    if (($pagenow === 'edit.php' && $pt === 'rk_galerija') || ($pagenow === 'edit-tags.php' && $tx === 'rk_gal_kat') || ($pagenow === 'post-new.php' && $pt === 'rk_galerija')) {
        wp_safe_redirect(admin_url('admin.php?page=rk-galerija')); exit;
    }
});
add_action('admin_head', function () {
    $s = get_current_screen();
    if ($s && $s->id === 'toplevel_page_rk-galerija') echo '<style>.update-nag,.notice:not(.rkg-keep),#wpfooter{display:none!important}#wpbody-content{padding-bottom:0}</style>';
});
add_filter('register_post_type_args', function ($args, $type) {
    if ($type === 'rk_galerija') { $args['show_in_menu'] = false; }
    return $args;
}, 10, 2);
// isvalyti Elementor kesa puslapiams, kuriuose rodoma galerija (kad pakeitimai matytusi is karto)
function rk_galui_purge() {
    foreach (get_terms(array('taxonomy' => 'rk_gal_kat', 'hide_empty' => false)) as $t) { $p = (int) get_term_meta($t->term_id, 'rk_page', true); if ($p) delete_post_meta($p, '_elementor_element_cache'); }
    $g = get_page_by_path('galerija'); if ($g) delete_post_meta($g->ID, '_elementor_element_cache');
}
add_action('save_post_rk_galerija', 'rk_galui_purge'); add_action('deleted_post', 'rk_galui_purge'); add_action('trashed_post', 'rk_galui_purge'); add_action('untrashed_post', 'rk_galui_purge'); add_action('edited_rk_gal_kat', 'rk_galui_purge'); add_action('delete_rk_gal_kat', 'rk_galui_purge');
function rk_galui_page() {
    $nonce = wp_create_nonce('wp_rest');
    ?>
<div id="rkg-app" class="rkg-app">
  <style>
  #wpcontent{background:#F4F7F5}.rkg-app{--g:#166534;--gd:#14532D;--acc:#22C55E;--tx:#111827;--mut:#64748B;--line:#E2E8F0;font-family:Inter,"Segoe UI",system-ui,sans-serif;color:var(--tx);margin:0 20px 90px 0;max-width:1440px}
  .rkg-app *{box-sizing:border-box}.rkg-app button{font-family:inherit}
  .rkg-top{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:24px 0 16px;flex-wrap:wrap}
  .rkg-top h1{margin:0;font-size:26px;font-weight:800;letter-spacing:-.01em;display:flex;align-items:center;gap:12px}.rkg-top h1 .ic{width:42px;height:42px;border-radius:12px;background:var(--g);color:#fff;display:grid;place-items:center}
  .rkg-top p{margin:6px 0 0;color:var(--mut);font-size:13.5px}.rkg-top p b{color:var(--g)}
  .rkg-btn{display:inline-flex;align-items:center;gap:8px;padding:11px 18px;border-radius:11px;font-weight:700;font-size:13.5px;border:1.5px solid transparent;cursor:pointer;line-height:1;transition:.15s;white-space:nowrap}
  .rkg-btn.p{background:var(--acc);color:#052E16}.rkg-btn.p:hover{background:#16a34a}.rkg-btn.g{background:var(--g);color:#fff}.rkg-btn.g:hover{background:var(--gd)}.rkg-btn.o{background:#fff;color:var(--g);border-color:var(--line)}.rkg-btn.o:hover{border-color:var(--g)}.rkg-btn.d{background:#fff;color:#b91c1c;border-color:#fecaca}.rkg-btn.d:hover{background:#fef2f2}.rkg-btn.s{padding:8px 12px;font-size:12.5px;border-radius:9px}.rkg-btn:disabled{opacity:.45;cursor:default}
  .rkg-help{background:#fff;border:1px solid var(--line);border-radius:16px;padding:16px 18px;margin-bottom:16px;display:none}.rkg-help.on{display:block}.rkg-help h3{margin:0 0 10px;font-size:15px}.rkg-help ol{margin:0;padding:0;list-style:none;display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.rkg-help li{display:flex;gap:10px;font-size:13px;color:#334155;line-height:1.45}.rkg-help li i{flex:0 0 26px;height:26px;border-radius:50%;background:#F0FDF4;color:var(--g);font-style:normal;font-weight:800;display:grid;place-items:center;font-size:12px}
  .rkg-lay{display:grid;grid-template-columns:260px 1fr;gap:16px;align-items:start}@media(max-width:1100px){.rkg-lay{grid-template-columns:1fr}}
  .rkg-side{background:#fff;border:1px solid var(--line);border-radius:16px;padding:12px;position:sticky;top:46px}.rkg-side h4{margin:4px 8px 8px;font-size:11.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--mut)}
  .rkg-cat{display:flex;align-items:center;gap:10px;width:100%;text-align:left;padding:10px 12px;border-radius:11px;border:1.5px solid transparent;background:transparent;cursor:pointer;font-size:13.5px;font-weight:600;color:var(--tx);transition:.15s}.rkg-cat:hover{background:#F8FAFC}.rkg-cat.on{background:var(--g);color:#fff}.rkg-cat b{margin-left:auto;background:#F0FDF4;color:var(--g);border-radius:999px;padding:2px 9px;font-size:11.5px;font-weight:700}.rkg-cat.on b{background:rgba(255,255,255,.18);color:#fff}.rkg-cat .pg{display:block;font-size:11px;font-weight:500;color:var(--mut);margin-top:1px}.rkg-cat.on .pg{color:#cfe6d8}.rkg-cat .dot{width:8px;height:8px;border-radius:50%;background:#E2E8F0;flex:0 0 auto}.rkg-cat .dot.ok{background:var(--acc)}
  .rkg-cat.add{border:1.5px dashed var(--line);color:var(--mut);justify-content:center;margin-top:8px}.rkg-cat.add:hover{border-color:var(--g);color:var(--g)}
  .rkg-side .foot{border-top:1px solid var(--line);margin-top:10px;padding-top:10px;display:flex;flex-direction:column;gap:6px}
  .rkg-main{min-width:0}
  .rkg-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:12px}.rkg-head h2{margin:0;font-size:20px;font-weight:800;display:flex;align-items:center;gap:10px}.rkg-head h2 small{font-size:12.5px;color:var(--mut);font-weight:600}.rkg-head .r{display:flex;gap:8px;flex-wrap:wrap;align-items:center}
  .rkg-drop{border:2px dashed #BBF7D0;background:#F0FDF4;border-radius:16px;padding:22px;text-align:center;color:var(--g);font-weight:700;margin-bottom:14px;cursor:pointer;transition:.15s;font-size:14px}.rkg-drop:hover,.rkg-drop.over{background:#DCFCE7;border-color:var(--acc)}.rkg-drop small{display:block;color:var(--mut);font-weight:500;margin-top:4px;font-size:12.5px}
  .rkg-up{display:none;background:#fff;border:1px solid var(--line);border-radius:14px;padding:12px 14px;margin-bottom:14px}.rkg-up.on{display:block}.rkg-up .row{display:flex;align-items:center;gap:10px;font-size:12.5px;padding:5px 0}.rkg-up .row img{width:34px;height:26px;object-fit:cover;border-radius:5px;background:#f1f5f9}.rkg-up .row .bar{flex:1;height:6px;background:#E2E8F0;border-radius:6px;overflow:hidden}.rkg-up .row .bar i{display:block;height:100%;width:0;background:var(--acc);transition:.2s}.rkg-up .row .st{width:70px;text-align:right;color:var(--mut);font-weight:600}.rkg-up .row.ok .st{color:var(--g)}.rkg-up .row.err .st{color:#b91c1c}
  .rkg-bar{display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap;background:#fff;border:1px solid var(--line);border-radius:14px;padding:10px 12px;margin-bottom:14px}.rkg-bar .l{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.rkg-bar input[type=text]{border:1.5px solid var(--line);border-radius:9px;padding:8px 10px 8px 32px;font-size:13px;background:#fff url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%2364748B' stroke-width='2'%3E%3Ccircle cx='11' cy='11' r='7'/%3E%3Cpath d='M20 20l-3.5-3.5'/%3E%3C/svg%3E") 10px center no-repeat;min-height:36px;width:220px}.rkg-bar .chk{display:inline-flex;align-items:center;gap:6px;font-size:12.5px;font-weight:600;color:var(--mut);cursor:pointer}.rkg-bar .chk input{accent-color:var(--g);width:16px;height:16px;margin:0}
  .rkg-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}
  .rkg-card{background:#fff;border:1px solid var(--line);border-radius:14px;overflow:hidden;position:relative;transition:.15s;display:flex;flex-direction:column}.rkg-card:hover{box-shadow:0 18px 40px -22px rgba(15,74,40,.35)}.rkg-card.sel{outline:2px solid var(--g);outline-offset:-2px}.rkg-card.drag{opacity:.4}.rkg-card.overd{outline:2px dashed var(--acc);outline-offset:-2px}.rkg-card.new{animation:rkgpop .5s}@keyframes rkgpop{from{transform:scale(.96);box-shadow:0 0 0 4px #BBF7D0}to{transform:none}}
  .rkg-card .ph{aspect-ratio:4/3;background:#f1f5f9 center/cover no-repeat;cursor:grab;position:relative}.rkg-card .ph .n{position:absolute;left:10px;top:10px;background:rgba(17,24,39,.65);color:#fff;font-size:11px;font-weight:700;padding:3px 8px;border-radius:999px}
  .rkg-card .ph .ck{position:absolute;left:10px;bottom:10px;opacity:0;transition:.15s}.rkg-card:hover .ph .ck,.rkg-card.sel .ph .ck{opacity:1}.rkg-card .ph .ck input{width:20px;height:20px;margin:0;accent-color:var(--g);cursor:pointer}
  .rkg-card .ph .tools{position:absolute;right:8px;top:8px;display:flex;gap:6px;opacity:0;transition:.15s}.rkg-card:hover .ph .tools{opacity:1}.rkg-card .ph .tools button{width:30px;height:30px;border-radius:50%;background:rgba(255,255,255,.95);border:0;color:var(--g);cursor:pointer;display:grid;place-items:center;font-size:14px;line-height:1}.rkg-card .ph .tools button.x{color:#b91c1c}.rkg-card .ph .tools button:hover{background:#fff;transform:scale(1.06)}
  .rkg-card .ph .mv{position:absolute;right:8px;bottom:8px;display:flex;gap:4px;opacity:0;transition:.15s}.rkg-card:hover .ph .mv{opacity:1}.rkg-card .ph .mv button{width:26px;height:26px;border-radius:7px;background:rgba(255,255,255,.95);border:0;color:var(--tx);cursor:pointer;font-size:12px;display:grid;place-items:center}.rkg-card .ph .mv button:disabled{opacity:.35}
  .rkg-card .bd{padding:10px 12px 12px;display:flex;flex-direction:column;gap:6px}.rkg-card textarea{width:100%;border:1.5px solid transparent;border-radius:8px;padding:7px 9px;font:600 13px/1.35 inherit;resize:none;background:#F8FAFC;color:var(--tx);min-height:46px}.rkg-card textarea:focus{border-color:var(--acc);background:#fff;outline:0}.rkg-card textarea.empty{background:#FFF7ED;border-color:#FED7AA}
  .rkg-card .st{font-size:11px;color:var(--mut);font-weight:600;min-height:14px;display:flex;justify-content:space-between;align-items:center}.rkg-card .st .ok{color:var(--g)}.rkg-card .st .warn{color:#c2410c}
  .rkg-empty{padding:56px 20px;text-align:center;color:var(--mut);background:#fff;border:1px solid var(--line);border-radius:14px;grid-column:1/-1}.rkg-empty b{display:block;color:var(--tx);font-size:16px;margin-bottom:6px}
  .rkg-skel{height:230px;border-radius:14px;background:linear-gradient(90deg,#eef2f1 25%,#f7faf8 50%,#eef2f1 75%);background-size:200% 100%;animation:rkgsk 1.2s infinite}@keyframes rkgsk{to{background-position:-200% 0}}
  .rkg-bulk{position:fixed;left:50%;bottom:22px;transform:translate(-50%,120%);background:#111827;color:#fff;border-radius:14px;padding:10px 12px 10px 16px;display:flex;align-items:center;gap:10px;box-shadow:0 20px 50px rgba(0,0,0,.35);z-index:99990;transition:.25s;font-size:13.5px;font-weight:600;flex-wrap:wrap}.rkg-bulk.on{transform:translate(-50%,0)}.rkg-bulk select{border:0;border-radius:8px;padding:7px 9px;font-size:13px}.rkg-bulk .rkg-btn{padding:8px 12px;font-size:12.5px}
  .rkg-toast{position:fixed;right:24px;bottom:24px;background:var(--g);color:#fff;padding:12px 16px;border-radius:12px;font-weight:600;font-size:13.5px;box-shadow:0 12px 30px rgba(0,0,0,.2);opacity:0;transform:translateY(10px);transition:.25s;z-index:99999;display:flex;align-items:center;gap:12px}.rkg-toast.on{opacity:1;transform:none}.rkg-toast.err{background:#b91c1c}.rkg-toast button{background:rgba(255,255,255,.18);border:0;color:#fff;border-radius:8px;padding:6px 10px;font-weight:700;cursor:pointer}
  .rkg-modal{position:fixed;inset:0;background:rgba(17,24,39,.5);display:none;place-items:center;z-index:99998}.rkg-modal.on{display:grid}.rkg-modal .box{background:#fff;border-radius:16px;padding:24px;width:min(480px,92vw);box-shadow:0 30px 60px rgba(0,0,0,.3)}.rkg-modal h3{margin:0 0 6px;font-size:18px}.rkg-modal p.h{margin:0 0 6px;color:var(--mut);font-size:12.5px}.rkg-modal label{display:block;font-size:12.5px;font-weight:600;color:var(--mut);margin:14px 0 5px}.rkg-modal input,.rkg-modal select{width:100%;border:1.5px solid var(--line);border-radius:9px;padding:9px 11px;font-size:14px}.rkg-modal .act{display:flex;gap:8px;justify-content:flex-end;margin-top:20px}
  .rkg-lb{position:fixed;inset:0;background:rgba(17,24,39,.92);display:none;place-items:center;z-index:999999}.rkg-lb.on{display:grid}.rkg-lb figure{margin:0;max-width:92vw;text-align:center}.rkg-lb img{max-width:92vw;max-height:80vh;border-radius:12px;box-shadow:0 30px 80px rgba(0,0,0,.5)}.rkg-lb figcaption{color:#fff;margin-top:14px;font-weight:600;font-size:14px}.rkg-lb button{position:absolute;background:rgba(255,255,255,.12);color:#fff;border:0;width:48px;height:48px;border-radius:50%;font-size:26px;cursor:pointer;display:grid;place-items:center}.rkg-lb button:hover{background:rgba(255,255,255,.25)}.rkg-lb .lb-x{top:20px;right:20px;font-size:18px}.rkg-lb .lb-p{left:20px;top:50%;transform:translateY(-50%)}.rkg-lb .lb-n{right:20px;top:50%;transform:translateY(-50%)}
  </style>
  <div class="rkg-top">
    <div><h1><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg></span>Galerija</h1><p id="rkg-sum">Kraunama…</p></div>
    <div style="display:flex;gap:8px;flex-wrap:wrap"><button class="rkg-btn o" id="rkg-helpbtn">? Kaip naudotis</button><a class="rkg-btn o" id="rkg-viewall" target="_blank">Visa galerija ↗</a><button class="rkg-btn p" id="rkg-upload"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><path d="M12 5v14M5 12h14"/></svg>Įkelti nuotraukas</button></div>
  </div>
  <div class="rkg-help" id="rkg-help"><h3>Kaip naudotis galerija</h3><ol>
    <li><i>1</i><span><b>Pasirinkite kategoriją</b> kairėje (arba sukurkite naują). Kiekviena kategorija rodoma pasirinktame paslaugos puslapyje.</span></li>
    <li><i>2</i><span><b>Įkelkite nuotraukas</b> – tempkite jas į žalią lauką arba spauskite „Įkelti nuotraukas“. Galima daug iš karto; didelės nuotraukos sumažinamos automatiškai.</span></li>
    <li><i>3</i><span><b>Įrašykite aprašymą</b> po kiekviena nuotrauka (pvz. „Audi A4 2019 m. antro rakto gamyba“). Išsaugoma automatiškai. Eiliškumą keiskite rodyklėmis ↑ ↓ arba tempdami.</span></li>
  </ol></div>
  <div class="rkg-lay">
    <aside class="rkg-side"><h4>Kategorijos</h4><div id="rkg-cats"></div><button class="rkg-cat add" id="rkg-cat-new">+ Nauja kategorija</button><div class="foot"><button class="rkg-btn o s" id="rkg-cat-edit">⚙ Kategorijos nustatymai</button></div></aside>
    <section class="rkg-main">
      <div class="rkg-head"><h2 id="rkg-title">…</h2><div class="r"><a id="rkg-view" class="rkg-btn o s" target="_blank">Peržiūrėti puslapį ↗</a></div></div>
      <div class="rkg-drop" id="rkg-drop">Tempkite nuotraukas čia arba spauskite „Įkelti nuotraukas“<small>JPG, PNG, HEIC/WEBP · daug iš karto · pateks į pasirinktą kategoriją</small></div>
      <div class="rkg-up" id="rkg-up"></div>
      <div class="rkg-bar"><div class="l"><label class="chk"><input type="checkbox" id="rkg-selall"> Pažymėti visas</label><span id="rkg-count" style="font-weight:700;font-size:13px"></span><label class="chk"><input type="checkbox" id="rkg-noempty"> tik be aprašymo</label></div><div class="l"><input type="text" id="rkg-q" placeholder="Ieškoti pagal aprašymą…"></div></div>
      <div class="rkg-grid" id="rkg-grid"><div class="rkg-skel"></div><div class="rkg-skel"></div><div class="rkg-skel"></div><div class="rkg-skel"></div></div>
    </section>
  </div>
  <div class="rkg-bulk" id="rkg-bulk"><span>Pažymėta: <b id="rkg-bulk-n">0</b></span><select id="rkg-bulk-cat"></select><button class="rkg-btn g" id="rkg-bulk-move">Perkelti</button><button class="rkg-btn d" id="rkg-bulk-del">Ištrinti</button><button class="rkg-btn o" id="rkg-bulk-x">Atžymėti</button></div>
  <div class="rkg-modal" id="rkg-modal"><div class="box"><h3 id="rkg-m-title">Kategorija</h3><p class="h">Kategorija – tai nuotraukų grupė, rodoma viename paslaugos puslapyje.</p><label>Pavadinimas</label><input type="text" id="rkg-m-name" placeholder="pvz. Raktų gamyba"><label>Rodyti puslapyje</label><select id="rkg-m-page"></select><div class="act"><button class="rkg-btn d" id="rkg-m-del" style="margin-right:auto">Ištrinti kategoriją</button><button class="rkg-btn o" id="rkg-m-cancel">Atšaukti</button><button class="rkg-btn g" id="rkg-m-save">Išsaugoti</button></div></div></div>
  <div class="rkg-toast" id="rkg-toast"></div>
  <input type="file" id="rkg-file" multiple accept="image/*" style="display:none">
</div>
<script>
(function(){
var N='<?php echo esc_js($nonce); ?>', REST='<?php echo esc_js(rest_url()); ?>', SITE='<?php echo esc_js(home_url('/')); ?>';
var H={'X-WP-Nonce':N,'Content-Type':'application/json'};
var S={cats:[],pages:[],items:[],media:{},cat:null,q:'',noempty:false,editCat:null,sel:new Set(),newIds:new Set()};
var $=function(s){return document.querySelector(s)};
function toast(t,err,action){var e=$('#rkg-toast');e.innerHTML='';e.appendChild(document.createTextNode(t));if(action){var b=document.createElement('button');b.textContent=action.label;b.onclick=function(){e.className='rkg-toast';action.fn()};e.appendChild(b)}e.className='rkg-toast on'+(err?' err':'');clearTimeout(e._t);e._t=setTimeout(function(){e.className='rkg-toast'},action?7000:2600);}
async function api(p,o){o=o||{};o.headers=Object.assign({},H,o.headers||{});o.credentials='same-origin';var r=await fetch(REST+p,o);if(!r.ok){var t=await r.text();throw new Error(r.status+' '+t.slice(0,140));}return r.status===204?null:r.json();}
async function all(p){var out=[],pg=1;while(true){var r=await fetch(REST+p+(p.indexOf('?')>0?'&':'?')+'per_page=100&page='+pg,{headers:H,credentials:'same-origin'});if(!r.ok)break;var d=await r.json();out=out.concat(d);if(d.length<100)break;pg++;}return out;}
function decode(s){var d=document.createElement('textarea');d.innerHTML=s;return d.value;}
function pageOf(cat){var id=cat&&cat.meta&&cat.meta.rk_page;return S.pages.filter(function(x){return x.id==id})[0];}
function curCat(){return S.cats.filter(function(c){return c.id===S.cat})[0];}
async function load(keep){var cats=all('wp/v2/rk_gal_kat?hide_empty=false&_fields=id,name,count,meta'),pages=all('wp/v2/pages?_fields=id,title,link,slug&status=publish'),items=all('wp/v2/rk_galerija?_fields=id,title,featured_media,rk_gal_kat,menu_order&orderby=menu_order&order=asc');S.cats=await cats;S.pages=await pages;S.items=await items;
 var ids=S.items.map(function(i){return i.featured_media}).filter(function(id){return id&&!S.media[id]});for(var i=0;i<ids.length;i+=100){var m=await all('wp/v2/media?include='+ids.slice(i,i+100).join(',')+'&_fields=id,source_url,media_details');m.forEach(function(x){var s=x.media_details&&x.media_details.sizes;S.media[x.id]=(s&&(s.medium_large||s.large||s.medium)||{}).source_url||x.source_url;});}
 var order={}; S.cats.forEach(function(c){order[c.id]=pageOf(c)?0:1}); S.cats.sort(function(a,b){return order[a.id]-order[b.id]||(pageOf(a)&&pageOf(b)?pageOf(a).id-pageOf(b).id:0)||a.name.localeCompare(b.name)});
 if((S.cat===null||!curCat())&&S.cats.length)S.cat=S.cats[0].id;var g=S.pages.filter(function(p){return p.slug==='galerija'})[0];var v=$('#rkg-viewall');if(g){v.href=g.link;v.style.display=''}else v.style.display='none';render();}
function render(){var noCap=S.items.filter(function(i){return !decode(i.title.rendered).trim()||/^darbu pavyzdys$/i.test(decode(i.title.rendered).trim())}).length;
 $('#rkg-sum').innerHTML='<b>'+S.items.length+'</b> nuotr. · <b>'+S.cats.length+'</b> kategorijos'+(noCap?' · <span style="color:#c2410c">'+noCap+' be aprašymo</span>':' · visos su aprašymais ✓');
 var cs=$('#rkg-cats');cs.innerHTML='';S.cats.forEach(function(c){var b=document.createElement('button');b.className='rkg-cat'+(c.id===S.cat?' on':'');var pg=pageOf(c);b.innerHTML='<span class="dot'+(pg?' ok':'')+'"></span><span>'+c.name+'<span class="pg">'+(pg?pg.title.rendered:'nerodoma svetainėje')+'</span></span><b>'+c.count+'</b>';b.onclick=function(){S.cat=c.id;S.sel.clear();bulk();render();};cs.appendChild(b);});
 var cat=curCat();var pg=pageOf(cat);$('#rkg-title').innerHTML=(cat?cat.name:'—')+' <small>'+(pg?'rodoma puslapyje „'+pg.title.rendered+'“':'nepriskirta puslapiui – nustatykite per ⚙')+'</small>';var v=$('#rkg-view');if(pg){v.href=pg.link;v.style.display=''}else v.style.display='none';
 var q=S.q.toLowerCase();var list=S.items.filter(function(i){if(i.rk_gal_kat.indexOf(S.cat)<0)return false;var t=decode(i.title.rendered);if(q&&t.toLowerCase().indexOf(q)<0)return false;if(S.noempty&&t.trim()&&!/^darbu pavyzdys$/i.test(t.trim()))return false;return true;});S.list=list;$('#rkg-count').textContent=list.length+' nuotr.';$('#rkg-selall').checked=list.length>0&&list.every(function(i){return S.sel.has(i.id)});
 var g=$('#rkg-grid');g.innerHTML='';if(!list.length){g.innerHTML='<div class="rkg-empty"><b>'+(S.q||S.noempty?'Nieko nerasta':'Čia dar nėra nuotraukų')+'</b>'+(S.q||S.noempty?'Pabandykite kitą paiešką arba nuimkite filtrą.':'Tempkite nuotraukas į žalią lauką viršuje – jos atsiras čia ir svetainėje.')+'</div>';return;}
 list.forEach(function(it,idx){var c=document.createElement('div');c.className='rkg-card'+(S.sel.has(it.id)?' sel':'')+(S.newIds.has(it.id)?' new':'');c.draggable=true;c.dataset.id=it.id;var url=S.media[it.featured_media]||'';var cap=decode(it.title.rendered);var isEmpty=!cap.trim()||/^darbu pavyzdys$/i.test(cap.trim());
  c.innerHTML='<div class="ph" style="background-image:url(\''+url+'\')"><span class="n">'+(idx+1)+'</span><label class="ck"><input type="checkbox"'+(S.sel.has(it.id)?' checked':'')+'></label><div class="tools"><button class="z" title="Padidinti">⤢</button><button class="x" title="Ištrinti">✕</button></div><div class="mv"><button class="up" title="Į priekį"'+(idx===0?' disabled':'')+'>↑</button><button class="dn" title="Toliau"'+(idx===list.length-1?' disabled':'')+'>↓</button></div></div><div class="bd"><textarea class="'+(isEmpty?'empty':'')+'" placeholder="Aprašymas po nuotrauka, pvz. „Audi A4 2019 m. antro rakto gamyba“"></textarea><div class="st"><span class="msg">'+(isEmpty?'<span class="warn">Įrašykite aprašymą</span>':'')+'</span></div></div>';
  var ta=c.querySelector('textarea');ta.value=isEmpty?'':cap;var msg=c.querySelector('.msg');var t;ta.addEventListener('input',function(){clearTimeout(t);msg.textContent='Rašoma…';ta.classList.toggle('empty',!ta.value.trim());t=setTimeout(save,700)});ta.addEventListener('blur',function(){clearTimeout(t);save()});
  async function save(){var v=ta.value.trim();if(v===cap)return;try{await api('wp/v2/rk_galerija/'+it.id,{method:'POST',body:JSON.stringify({title:v})});it.title.rendered=v;cap=v;msg.innerHTML=v?'<span class="ok">Išsaugota ✓</span>':'<span class="warn">Įrašykite aprašymą</span>';setTimeout(function(){if(msg.textContent==='Išsaugota ✓')msg.textContent=''},2000);$('#rkg-sum').textContent='';render_sum();}catch(e){msg.innerHTML='<span class="warn">Nepavyko išsaugoti</span>';toast('Klaida: '+e.message,1)}}
  c.querySelector('.z').onclick=function(){lightbox(list,idx)};c.querySelector('.ck input').onchange=function(){if(this.checked)S.sel.add(it.id);else S.sel.delete(it.id);c.classList.toggle('sel',this.checked);bulk();$('#rkg-selall').checked=list.every(function(i){return S.sel.has(i.id)})};
  c.querySelector('.x').onclick=function(){del([it.id])};
  c.querySelector('.up').onclick=function(){move(list,idx,idx-1)};c.querySelector('.dn').onclick=function(){move(list,idx,idx+1)};
  c.addEventListener('dragstart',function(e){S.drag=it.id;c.classList.add('drag');e.dataTransfer.effectAllowed='move'});c.addEventListener('dragend',function(){c.classList.remove('drag');document.querySelectorAll('.overd').forEach(function(x){x.classList.remove('overd')})});
  c.addEventListener('dragover',function(e){e.preventDefault();c.classList.add('overd')});c.addEventListener('dragleave',function(){c.classList.remove('overd')});
  c.addEventListener('drop',function(e){e.preventDefault();c.classList.remove('overd');if(S.drag===it.id)return;var from=list.findIndex(function(x){return x.id===S.drag}),to=list.findIndex(function(x){return x.id===it.id});move(list,from,to)});
  g.appendChild(c);});S.newIds.clear();}
function render_sum(){var noCap=S.items.filter(function(i){var t=decode(i.title.rendered).trim();return !t||/^darbu pavyzdys$/i.test(t)}).length;$('#rkg-sum').innerHTML='<b>'+S.items.length+'</b> nuotr. · <b>'+S.cats.length+'</b> kategorijos'+(noCap?' · <span style="color:#c2410c">'+noCap+' be aprašymo</span>':' · visos su aprašymais ✓');}
async function move(list,from,to){if(to<0||to>=list.length)return;var m=list.splice(from,1)[0];list.splice(to,0,m);render();try{for(var i=0;i<list.length;i++){if(list[i].menu_order!==i+1){await api('wp/v2/rk_galerija/'+list[i].id,{method:'POST',body:JSON.stringify({menu_order:i+1})});list[i].menu_order=i+1;}}toast('Eiliškumas išsaugotas');}catch(e){toast('Klaida: '+e.message,1)}}
async function del(ids){var n=0;for(const id of ids){try{await api('wp/v2/rk_galerija/'+id,{method:'DELETE'});n++;}catch(e){}}S.sel.clear();bulk();await load();toast('Pašalinta: '+n+' nuotr.',0,{label:'Atšaukti',fn:async function(){for(const id of ids){try{await api('wp/v2/rk_galerija/'+id,{method:'POST',body:JSON.stringify({status:'publish'})})}catch(e){}}await load();toast('Grąžinta');}});}
function bulk(){var b=$('#rkg-bulk');$('#rkg-bulk-n').textContent=S.sel.size;b.classList.toggle('on',S.sel.size>0);var s=$('#rkg-bulk-cat');s.innerHTML='';S.cats.forEach(function(c){if(c.id===S.cat)return;var o=document.createElement('option');o.value=c.id;o.textContent='→ '+c.name;s.appendChild(o)});$('#rkg-bulk-move').disabled=!s.options.length;}
$('#rkg-bulk-x').onclick=function(){S.sel.clear();bulk();render()};$('#rkg-bulk-del').onclick=function(){if(!confirm('Pašalinti '+S.sel.size+' pažymėtas nuotraukas iš galerijos?'))return;del(Array.from(S.sel))};
$('#rkg-bulk-move').onclick=async function(){var to=+$('#rkg-bulk-cat').value;if(!to)return;var n=0;for(const id of S.sel){try{await api('wp/v2/rk_galerija/'+id,{method:'POST',body:JSON.stringify({rk_gal_kat:[to]})});n++;}catch(e){}}S.sel.clear();bulk();await load();toast('Perkelta: '+n+' nuotr.');};
$('#rkg-selall').onchange=function(){var on=this.checked;(S.list||[]).forEach(function(i){if(on)S.sel.add(i.id);else S.sel.delete(i.id)});bulk();render()};
$('#rkg-q').addEventListener('input',function(){S.q=this.value;render()});$('#rkg-noempty').onchange=function(){S.noempty=this.checked;render()};
$('#rkg-helpbtn').onclick=function(){var h=$('#rkg-help');h.classList.toggle('on');try{localStorage.setItem('rkg_help',h.classList.contains('on')?'1':'0')}catch(e){}};try{if(localStorage.getItem('rkg_help')!=='0')$('#rkg-help').classList.add('on')}catch(e){$('#rkg-help').classList.add('on')}
function lightbox(list,i){var m=$('#rkg-lb');if(!m){m=document.createElement('div');m.id='rkg-lb';m.className='rkg-lb';m.innerHTML='<button class="lb-x">✕</button><button class="lb-p">‹</button><button class="lb-n">›</button><figure><img><figcaption></figcaption></figure>';document.body.appendChild(m);m.querySelector('.lb-x').onclick=function(){m.classList.remove('on')};m.onclick=function(e){if(e.target===m)m.classList.remove('on')};document.addEventListener('keydown',function(e){if(!m.classList.contains('on'))return;if(e.key==='Escape')m.classList.remove('on');if(e.key==='ArrowRight')m._n();if(e.key==='ArrowLeft')m._p();});}
 function show(k){k=(k+list.length)%list.length;m._i=k;var it=list[k];m.querySelector('img').src=S.media[it.featured_media]||'';m.querySelector('figcaption').textContent=(k+1)+' / '+list.length+' · '+decode(it.title.rendered);}
 m._n=function(){show(m._i+1)};m._p=function(){show(m._i-1)};m.querySelector('.lb-n').onclick=m._n;m.querySelector('.lb-p').onclick=m._p;show(i);m.classList.add('on');}
// ikelimas: sumazinimas iki 2000px, 3 lygiagreciai, per-failo progresas
var drop=$('#rkg-drop'),file=$('#rkg-file');$('#rkg-upload').onclick=function(){file.click()};drop.onclick=function(){file.click()};
drop.addEventListener('dragover',function(e){e.preventDefault();drop.classList.add('over')});drop.addEventListener('dragleave',function(){drop.classList.remove('over')});drop.addEventListener('drop',function(e){e.preventDefault();drop.classList.remove('over');up(e.dataTransfer.files)});file.addEventListener('change',function(){up(file.files);file.value=''});
document.addEventListener('dragover',function(e){if(e.dataTransfer&&e.dataTransfer.types&&e.dataTransfer.types.indexOf('Files')>=0){e.preventDefault();drop.classList.add('over')}});document.addEventListener('drop',function(e){if(e.target.closest&&e.target.closest('#rkg-drop'))return;if(e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files.length){e.preventDefault();drop.classList.remove('over');up(e.dataTransfer.files)}});
function shrink(f){return new Promise(function(res){if(!/^image\/(jpeg|png|webp)$/.test(f.type)||f.size<600*1024)return res(f);var img=new Image();var u=URL.createObjectURL(f);img.onload=function(){var MAX=2000,w=img.width,h=img.height;if(Math.max(w,h)<=MAX&&f.size<2.5*1024*1024){URL.revokeObjectURL(u);return res(f)}var k=Math.min(1,MAX/Math.max(w,h));var cv=document.createElement('canvas');cv.width=Math.round(w*k);cv.height=Math.round(h*k);cv.getContext('2d').drawImage(img,0,0,cv.width,cv.height);cv.toBlob(function(b){URL.revokeObjectURL(u);if(!b)return res(f);var nf=new File([b],f.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'});res(nf.size<f.size?nf:f)},'image/jpeg',.86)};img.onerror=function(){URL.revokeObjectURL(u);res(f)};img.src=u;});}
function capFrom(name){var c=name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').trim();return /^(img|dsc|image|photo|pxl|screenshot)[\s\d]*$/i.test(c)?'':c;}
async function up(files){if(!S.cat){toast('Pirmiausia sukurkite kategoriją',1);return}files=[].slice.call(files).filter(function(f){return /^image\//.test(f.type)||/\.(heic|heif)$/i.test(f.name)});if(!files.length){toast('Pasirinkite nuotraukų failus (JPG, PNG…)',1);return}
 var box=$('#rkg-up');box.innerHTML='';box.classList.add('on');var rows=files.map(function(f){var r=document.createElement('div');r.className='row';r.innerHTML='<img><span style="width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+f.name+'</span><div class="bar"><i></i></div><span class="st">laukia</span>';box.appendChild(r);try{r.querySelector('img').src=URL.createObjectURL(f)}catch(e){}return r;});
 var max=S.items.reduce(function(m,i){return Math.max(m,i.menu_order||0)},0);var done=0,ok=0;var catId=S.cat;
 async function one(i){var f=files[i],r=rows[i],st=r.querySelector('.st'),bar=r.querySelector('.bar i');try{st.textContent='ruošiama';var g=await shrink(f);bar.style.width='30%';st.textContent='keliama';var fd=new FormData();fd.append('file',g,g.name);fd.append('title',capFrom(f.name)||'Darbu pavyzdys');var m=await new Promise(function(res,rej){var x=new XMLHttpRequest();x.open('POST',REST+'wp/v2/media');x.setRequestHeader('X-WP-Nonce',N);x.withCredentials=true;x.upload.onprogress=function(e){if(e.lengthComputable)bar.style.width=(30+Math.round(e.loaded/e.total*60))+'%'};x.onload=function(){x.status<300?res(JSON.parse(x.responseText)):rej(new Error(x.status))};x.onerror=function(){rej(new Error('tinklas'))};x.send(fd)});var p=await api('wp/v2/rk_galerija',{method:'POST',body:JSON.stringify({title:capFrom(f.name),status:'publish',featured_media:m.id,rk_gal_kat:[catId],menu_order:++max})});S.newIds.add(p.id);bar.style.width='100%';r.classList.add('ok');st.textContent='įkelta ✓';ok++;}catch(e){r.classList.add('err');st.textContent='klaida';bar.style.width='100%';bar.style.background='#fca5a5';}done++;}
 var q=files.map(function(_,i){return i});async function worker(){while(q.length){await one(q.shift())}}await Promise.all([worker(),worker(),worker()]);
 await load();toast(ok===files.length?'Įkelta: '+ok+' nuotr. Dabar įrašykite aprašymus.':'Įkelta '+ok+' iš '+files.length+' – kai kurių nepavyko',ok!==files.length);setTimeout(function(){box.classList.remove('on')},ok===files.length?2500:8000);var first=document.querySelector('.rkg-card.new');if(first)first.scrollIntoView({behavior:'smooth',block:'center'});}
// kategorijos
function openCat(c){S.editCat=c;$('#rkg-m-title').textContent=c?'Kategorijos nustatymai':'Nauja kategorija';$('#rkg-m-name').value=c?c.name:'';var s=$('#rkg-m-page');s.innerHTML='<option value="0">— nerodyti svetainėje —</option>';S.pages.forEach(function(p){if(p.slug==='galerija'||p.slug==='privatumo-politika')return;var o=document.createElement('option');o.value=p.id;o.textContent=p.title.rendered;if(c&&c.meta&&c.meta.rk_page==p.id)o.selected=true;s.appendChild(o)});$('#rkg-m-del').style.display=c?'':'none';$('#rkg-modal').classList.add('on');setTimeout(function(){$('#rkg-m-name').focus()},50);}
$('#rkg-cat-edit').onclick=function(){openCat(curCat()||null)};$('#rkg-cat-new').onclick=function(){openCat(null)};$('#rkg-m-cancel').onclick=function(){$('#rkg-modal').classList.remove('on')};$('#rkg-modal').addEventListener('click',function(e){if(e.target===this)this.classList.remove('on')});document.addEventListener('keydown',function(e){if(e.key==='Escape')$('#rkg-modal').classList.remove('on');if(e.key==='Enter'&&$('#rkg-modal').classList.contains('on')&&e.target.id==='rkg-m-name')$('#rkg-m-save').click()});
$('#rkg-m-save').onclick=async function(){var name=$('#rkg-m-name').value.trim();if(!name){toast('Įrašykite pavadinimą',1);return}var body={name:name,meta:{rk_page:+$('#rkg-m-page').value}};try{if(S.editCat){await api('wp/v2/rk_gal_kat/'+S.editCat.id,{method:'POST',body:JSON.stringify(body)})}else{var r=await api('wp/v2/rk_gal_kat',{method:'POST',body:JSON.stringify(body)});S.cat=r.id}$('#rkg-modal').classList.remove('on');toast('Kategorija išsaugota');await load();}catch(e){toast('Klaida: '+e.message,1)}};
$('#rkg-m-del').onclick=async function(){if(!S.editCat)return;if(!confirm('Ištrinti kategoriją „'+S.editCat.name+'“? Nuotraukos liks, bet nebebus rodomos svetainėje.'))return;try{await api('wp/v2/rk_gal_kat/'+S.editCat.id+'?force=true',{method:'DELETE'});$('#rkg-modal').classList.remove('on');S.cat=null;toast('Kategorija ištrinta');await load();}catch(e){toast('Klaida: '+e.message,1)}};
load().catch(function(e){toast('Nepavyko įkelti duomenų: '+e.message,1)});
})();
</script>
    <?php
}
